/**
 * 
 * @param {WRONG_ANSWER: number, SUCCESS: number, CPU_TIME_LIMIT_EXCEEDED: number, REAL_TIME_LIMIT_EXCEEDED: number, MEMORY_LIMIT_EXCEEDED: number} 
 */
const Result = {
  WRONG_ANSWER: -1,
  SUCCESS: 0,
  CPU_TIME_LIMIT_EXCEEDED: 1,
  REAL_TIME_LIMIT_EXCEEDED: 2,
  MEMORY_LIMIT_EXCEEDED: 3,
  RUNTIME_ERROR: 4,
  SYSTEM_ERROR: 5
}

module.exports = {
  Result,
}