const Koa = require('koa')
const InitManager = require('./core/init')
const parser = require('koa-bodyparser')
const catchError = require('./middlewares/exception')
const imageServer = require('koa-static')
const cor = require('@koa/cors')
const app = new Koa()

// require('./app/models/announcement')
// require('./app/models/class')
// require('./app/models/course')
// require('./app/models/chapter')
// require('./app/models/exercise')
// require('./app/models/experiment-submit')
// require('./app/models/experiments')
// require('./app/models/label')
// require('./app/models/course-category')
// require('./app/models/course-direction')
// require('./app/models/department')
// require('./app/models/major')
// require('./app/models/school')
// require('./app/models/student-info')
// require('./app/models/teacher-info')
// require('./app/models/university')
// require('./app/models/user')
// require('./app/models/course-content')
// require('./app/models/attend-exam')
// require('./app/models/exam-record')
// require('./app/models/exam')
// require('./app/models/exercise-collection')
// require('./app/models/homework')
// require('./app/models/paper_exercises')
// require('./app/models/paper')
// require('./app/models/student-chapter')
// require('./app/models/student-homework')

app.use(catchError)
app.use(parser())
app.use(cor())
app.use(imageServer(__dirname + '/upload'))

InitManager.initCore(app)

app.listen(8020)