const Koa = require('koa')
const InitManager = require('./core/init')
const parser = require('koa-bodyparser')
const catchError = require('./middlewares/exception')
const imageServer = require('koa-static')
const app = new Koa()

require('./app/models/announcement')
require('./app/models/class')
require('./app/models/course')
require('./app/models/course-category')
require('./app/models/course-direction')
require('./app/models/department')
require('./app/models/major')
require('./app/models/school')
require('./app/models/student-info')
require('./app/models/teacher-info')
require('./app/models/university')
require('./app/models/user')

app.use(catchError)
app.use(parser())
app.use(imageServer(__dirname + '/upload'))

InitManager.initCore(app)

app.listen(8020)